apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-templates
  description: Templates for Red Hat Developer Hub
  annotations:
    github.com/project-slug: kdilshan-fdo/rhdh-templates
spec:
  type: template
  lifecycle: experimental
  owner: web@example.com
